services:
  vitepress:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "${PORT:-5173}:5173"
    volumes:
      - ./:/app:cached
      - /app/node_modules
    restart: unless-stopped
